"""F4 Stage 2 Causal Evaluation Foundation Package.

Provides typed contracts, metric semantic statuses, evaluation statuses,
F4 invariant registry (F4-I001 through F4-I031), F4-1 Synthetic Statistical Simulation Harness,
F4-2 Production Causal Estimator, F4-3 Causal Evaluation Lifecycle & Safety Engine,
and F4-4 Forensic Evidence & Audit Bundle System.
"""

from .contracts import (
    ArmType,
    ClusteredUncertaintyMetric,
    DifferentialAttrition,
    EstimandPopulation,
    EvaluationStatus,
    F4EvaluationReport,
    F4Observation,
    F4PrimaryResult,
    F4Provenance,
    F4SecondaryMetrics,
    MetricSemanticStatus,
    OutcomeState,
    PopulationAccounting,
)
from .estimator import (
    ALLOWED_PRE_TREATMENT_FEATURES,
    FORBIDDEN_POST_TREATMENT_FEATURES,
    EstimatorDiagnosticResult,
    ProductionCausalEstimator,
)
from .evidence import (
    AssignmentEvidence,
    AttributionEvidence,
    ClusteredUncertaintyEvidence,
    ClusterEvidence,
    ConfigurationHashEvidence,
    EstimatorEvidence,
    EvidenceRecordMetadata,
    EvidenceVerificationStatus,
    F4EvidenceBundle,
    F4EvidenceGenerator,
    InvariantResult,
    IPWEvidence,
    LifecycleEvidence,
    MappingEvidence,
    MissingnessEvidence,
    OutcomeSemanticsEvidence,
    PopulationEvidence,
    PropensityFeatureEvidence,
    PropensityUncertaintyEvidence,
    TenantIsolationEvidence,
    VerifiedRevenueEvidence,
    VersionConsistencyEvidence,
)
from .invariants import (
    F4_INVARIANTS_REGISTRY,
    F4Invariant,
    get_invariant,
    list_invariants,
)
from .lifecycle import (
    F4EvaluationLifecycleEngine,
    LifecycleConfig,
)
from .simulation import (
    AllocationAdjustedEstimator,
    IndividualIPWEstimator,
    SimulationConfig,
    SimulationDiagnosticResult,
    SyntheticDataset,
    SyntheticExperimentGenerator,
    SyntheticGroundTruth,
    SyntheticPotentialOutcome,
    run_simulation,
)

__all__ = [
    "ArmType",
    "MetricSemanticStatus",
    "EvaluationStatus",
    "OutcomeState",
    "EstimandPopulation",
    "F4Observation",
    "DifferentialAttrition",
    "PopulationAccounting",
    "F4Provenance",
    "ClusteredUncertaintyMetric",
    "F4PrimaryResult",
    "F4SecondaryMetrics",
    "F4EvaluationReport",
    "F4Invariant",
    "F4_INVARIANT_REGISTRY",
    "get_invariant",
    "list_invariants",
    "SimulationConfig",
    "SyntheticGroundTruth",
    "SyntheticPotentialOutcome",
    "SyntheticDataset",
    "SimulationDiagnosticResult",
    "SyntheticExperimentGenerator",
    "AllocationAdjustedEstimator",
    "IndividualIPWEstimator",
    "ProductionCausalEstimator",
    "EstimatorDiagnosticResult",
    "ALLOWED_PRE_TREATMENT_FEATURES",
    "FORBIDDEN_POST_TREATMENT_FEATURES",
    "F4EvaluationLifecycleEngine",
    "LifecycleConfig",
    "EvidenceVerificationStatus",
    "EvidenceRecordMetadata",
    "PopulationEvidence",
    "AssignmentEvidence",
    "ClusterEvidence",
    "MappingEvidence",
    "OutcomeSemanticsEvidence",
    "VerifiedRevenueEvidence",
    "EstimatorEvidence",
    "IPWEvidence",
    "PropensityFeatureEvidence",
    "MissingnessEvidence",
    "ClusteredUncertaintyEvidence",
    "PropensityUncertaintyEvidence",
    "AttributionEvidence",
    "TenantIsolationEvidence",
    "VersionConsistencyEvidence",
    "ConfigurationHashEvidence",
    "LifecycleEvidence",
    "InvariantResult",
    "F4EvidenceBundle",
    "F4EvidenceGenerator",
    "run_simulation",
]
